name: Build & Deploy Stream Overlay

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # 1) Checkout (with LFS in case your MP4 is stored via Git LFS)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # 2) Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Use a real available version (adjust if you need)
          go-version: '1.23.x'
          cache: true

      # 3) Make build.sh executable and run it
      - name: Build site
        shell: bash
        run: |
          chmod +x ./build.sh
          ./build.sh

      # 4) Configure AWS creds (uses your repo secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5) Deploy ALL static files to the BUCKET ROOT
      #    This preserves your relative paths like css/overlay.css, assets/..., js/..., etc.
      - name: Deploy static site to S3 (bucket root)
        run: |
          aws s3 sync build/stream-overlay-web s3://david-portfolio-site/ --acl public-read --delete

      # OPTIONAL: If you front S3 with CloudFront, uncomment to invalidate
      # - name: Invalidate CloudFront
      #   run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
